
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdxgbopqyeuqonmmikfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkeGdib3BxeWV1cW9ubW1pa2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0NjQ4OTQsImV4cCI6MjA1OTA0MDg5NH0.InN_16DmJkPtXnxn-LAJfKWf-KbLy-Vg3vQdF8T7TPQ";

// Get current site URL for Supabase redirects
const getRedirectURL = () => {
  // Check if we're on the production domain
  const hostname = window.location.hostname;
  if (hostname === 'www.orbit-insights.com' || hostname === 'orbit-insights.com') {
    return 'https://www.orbit-insights.com/login';
  }
  
  // In development, use the local dev URL
  return `${window.location.origin}/login`;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a more flexible type that extends the generated Database type
export type ExtendedDatabase = Database & {
  public: {
    Tables: {
      assessment_responses: {
        Row: {
          id: string;
          assessment_id: string;
          rater_type: string;
          responses: any;
          email?: string | null;
          name?: string | null;
          completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          assessment_id: string;
          rater_type: string;
          responses?: any;
          email?: string | null;
          name?: string | null;
          completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          assessment_id?: string;
          rater_type?: string;
          responses?: any;
          email?: string | null;
          name?: string | null;
          completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};

// Create client with session persistence enabled
export const supabase = createClient<ExtendedDatabase>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: localStorage,
      flowType: 'pkce',
      redirectTo: getRedirectURL()
    }
  }
);
