
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://your-new-project-id.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "your-new-anon-key";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a more flexible type that extends the generated Database type
export type ExtendedDatabase = Database & {
  public: {
    Tables: {
      assessment_responses: {
        Row: {
          id: string;
          assessment_id: string;
          rater_type: string;
          responses: any;
          email?: string;
          name?: string;
          completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          assessment_id: string;
          rater_type: string;
          responses?: any;
          email?: string;
          name?: string;
          completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          assessment_id?: string;
          rater_type?: string;
          responses?: any;
          email?: string;
          name?: string;
          completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};

// Create client with session persistence enabled
export const supabase = createClient<ExtendedDatabase>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: localStorage
    }
  }
);
